# Generated by Django 4.2.16 on 2026-05-25 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP — Fuel Combustion'), ('SAP_PROCUREMENT', 'SAP — Procurement (non-fuel)'), ('UTILITY_ELECTRICITY', 'Utility — Electricity'), ('TRAVEL_AIR', 'Travel — Air'), ('TRAVEL_HOTEL', 'Travel — Hotel'), ('TRAVEL_GROUND', 'Travel — Ground Transport'), ('TRAVEL_RAIL', 'Travel — Rail')], max_length=30)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 — Direct'), ('2', 'Scope 2 — Indirect Energy'), ('3', 'Scope 3 — Value Chain')], max_length=1)),
                ('category', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('raw_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('raw_unit', models.CharField(max_length=50)),
                ('raw_location', models.CharField(blank=True, max_length=255)),
                ('source_record_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('raw_data', models.JSONField()),
                ('quantity_normalized', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_normalized', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('vendor_supplier', models.CharField(blank=True, max_length=255)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=100)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged — Needs Attention'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Audit')], db_index=True, default='PENDING', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('auto_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=30)),
                ('filename', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='raw_uploads/%Y/%m/')),
                ('row_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('parse_errors', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('PARTIAL', 'Partial — some rows failed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='analyst', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Record Created'), ('EDITED', 'Record Edited'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Audit'), ('BATCH_UPLOADED', 'Batch Uploaded'), ('BATCH_FAILED', 'Batch Parse Failed')], max_length=30)),
                ('actor', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.ingestionbatch')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.activityrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.client'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['client', 'status'], name='core_activi_client__ad1f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['client', 'scope'], name='core_activi_client__88a0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['client', 'source_type'], name='core_activi_client__802a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['batch', 'status'], name='core_activi_batch_i_87beec_idx'),
        ),
    ]
